PARAMS = {
    'figure' : {
        'size' : 10,
        'extra_space' : 0.7,
        'background' : 'white',
        'away' : 10,
    },
    'text' : {
        'x' : 0.3,
        'y' : 0.3,
        'fontsize' : 25,
        'colour' : 'black',
        'background' : 'lightcyan',
        'border' : 2,
    },
    'globe' : {
        'land_colour' : 'royalblue',
        'water_colour' : 'skyblue',
        'border' : 3,
        'border_colour' : 'midnightblue',
    },
    'shade' : {
        'land_colour' : 'chocolate',
        'water_colour' : 'peachpuff',
        'angle' : 170,
        'scale' : 0.7,
        'ratio' : 0.3,
        'rotation' : -75,
        'x_pos' : 0.9,
        'y_pos' : 0.1,
        'alpha' : 0.3,
    },
    'airports' : {
        'colour' : 'turquoise',
        'size' : 0.07,
        'border' : 0.7,
        'border_colour' : 'midnightblue',
    },
    'flights' : {
        'max_height' : 1.2,
        'delta_step' : 0.005,
        'size' : 3,
        'colour' : 'gold',
        'border' : 2,
        'border_colour' : 'midnightblue',
    },
    'airplanes' : {
        'n_indices' : 2,
        'size' : 7,
        'colour' : 'crimson',
        'border' : 3,
        'border_colour' : 'midnightblue',
    },
    'zorder' : {
        'background' : -2,
        'water' : 0.5,
        'land' : 1,
        'land_border' : 0.9,
        'shade_water' : -1,
        'shade_land' : -0.5,
        'airports' : 1.5,
        'flights' : 2,
        'flights_border' : 1.9,
        'airplanes' : 3,
    },
}